//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.15 at 10:20:40 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.lisa.org/srx20", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.sourceforge.segment.srx.io.bind;
